-- CreateTable
CREATE TABLE "User" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "email" TEXT NOT NULL,
    "passwordHash" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "role" TEXT NOT NULL DEFAULT 'editor',
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- CreateTable
CREATE TABLE "Artist" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "slug" TEXT NOT NULL,
    "stageName" TEXT NOT NULL,
    "realName" TEXT,
    "profileSummary" TEXT NOT NULL,
    "birthDate" DATETIME,
    "birthPlace" TEXT,
    "debutDate" DATETIME,
    "agency" TEXT,
    "fanClubName" TEXT,
    "officialWebsite" TEXT,
    "officialSocialLinks" TEXT NOT NULL DEFAULT '[]',
    "isSample" BOOLEAN NOT NULL DEFAULT false,
    "status" TEXT NOT NULL DEFAULT 'draft',
    "lastFactCheckedAt" DATETIME,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);

-- CreateTable
CREATE TABLE "Award" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "artistId" TEXT NOT NULL,
    "year" INTEGER,
    "title" TEXT NOT NULL,
    "org" TEXT,
    "sourceUrl" TEXT,
    CONSTRAINT "Award_artistId_fkey" FOREIGN KEY ("artistId") REFERENCES "Artist" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "TimelineEntry" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "artistId" TEXT NOT NULL,
    "date" DATETIME NOT NULL,
    "title" TEXT NOT NULL,
    "description" TEXT,
    "sourceUrl" TEXT,
    CONSTRAINT "TimelineEntry_artistId_fkey" FOREIGN KEY ("artistId") REFERENCES "Artist" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "Music" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "slug" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "type" TEXT NOT NULL DEFAULT 'single',
    "releaseDate" DATETIME,
    "label" TEXT,
    "description" TEXT,
    "trackList" TEXT NOT NULL DEFAULT '[]',
    "isSample" BOOLEAN NOT NULL DEFAULT false,
    "status" TEXT NOT NULL DEFAULT 'draft',
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);

-- CreateTable
CREATE TABLE "Program" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "slug" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "broadcaster" TEXT,
    "description" TEXT,
    "airInfo" TEXT,
    "isSample" BOOLEAN NOT NULL DEFAULT false,
    "status" TEXT NOT NULL DEFAULT 'draft',
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);

-- CreateTable
CREATE TABLE "Event" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "slug" TEXT NOT NULL,
    "eventName" TEXT NOT NULL,
    "eventType" TEXT NOT NULL DEFAULT 'concert',
    "startDateTime" DATETIME NOT NULL,
    "endDateTime" DATETIME,
    "venue" TEXT,
    "address" TEXT,
    "region" TEXT,
    "ticketVendor" TEXT,
    "ticketUrl" TEXT,
    "ticketOpenDate" DATETIME,
    "priceInformation" TEXT,
    "ageRestriction" TEXT,
    "organizer" TEXT,
    "officialSourceUrl" TEXT,
    "transportInfo" TEXT,
    "eventStatus" TEXT NOT NULL DEFAULT 'scheduled',
    "cancelledAt" DATETIME,
    "rescheduledFrom" DATETIME,
    "isSample" BOOLEAN NOT NULL DEFAULT false,
    "status" TEXT NOT NULL DEFAULT 'draft',
    "sourceCheckedAt" DATETIME,
    "lastUpdatedAt" DATETIME NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- CreateTable
CREATE TABLE "Article" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "type" TEXT NOT NULL DEFAULT 'news',
    "slug" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "seoTitle" TEXT,
    "description" TEXT NOT NULL,
    "excerpt" TEXT,
    "body" TEXT NOT NULL,
    "searchIntent" TEXT,
    "primaryKeyword" TEXT,
    "relatedKeywords" TEXT NOT NULL DEFAULT '[]',
    "categories" TEXT NOT NULL DEFAULT '[]',
    "tags" TEXT NOT NULL DEFAULT '[]',
    "publishedAt" DATETIME,
    "updatedAt" DATETIME NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "lastFactCheckedAt" DATETIME,
    "nextReviewAt" DATETIME,
    "timeSensitive" BOOLEAN NOT NULL DEFAULT false,
    "authorId" TEXT,
    "reviewerId" TEXT,
    "heroImage" TEXT,
    "heroImageAlt" TEXT,
    "isAiImage" BOOLEAN NOT NULL DEFAULT false,
    "status" TEXT NOT NULL DEFAULT 'draft',
    "canonical" TEXT,
    "index" BOOLEAN NOT NULL DEFAULT true,
    "riskLevel" TEXT NOT NULL DEFAULT 'low',
    "qualityScore" INTEGER,
    "qualityBreakdown" TEXT,
    "isSample" BOOLEAN NOT NULL DEFAULT false,
    "autoGenerated" BOOLEAN NOT NULL DEFAULT false,
    CONSTRAINT "Article_authorId_fkey" FOREIGN KEY ("authorId") REFERENCES "User" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "Article_reviewerId_fkey" FOREIGN KEY ("reviewerId") REFERENCES "User" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "Source" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "sourceTitle" TEXT NOT NULL,
    "sourcePublisher" TEXT,
    "sourceUrl" TEXT NOT NULL,
    "publishedAt" DATETIME,
    "accessedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "sourceGrade" TEXT NOT NULL DEFAULT 'B',
    "factType" TEXT,
    "quotedText" TEXT,
    "verificationStatus" TEXT NOT NULL DEFAULT 'unverified',
    "linkOk" BOOLEAN NOT NULL DEFAULT true,
    "articleId" TEXT,
    "artistId" TEXT,
    "eventId" TEXT,
    "musicId" TEXT,
    CONSTRAINT "Source_articleId_fkey" FOREIGN KEY ("articleId") REFERENCES "Article" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "Source_artistId_fkey" FOREIGN KEY ("artistId") REFERENCES "Artist" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "Source_eventId_fkey" FOREIGN KEY ("eventId") REFERENCES "Event" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "Source_musicId_fkey" FOREIGN KEY ("musicId") REFERENCES "Music" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "RevisionLog" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "articleId" TEXT NOT NULL,
    "changedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "changedBy" TEXT,
    "summary" TEXT NOT NULL,
    "diff" TEXT,
    CONSTRAINT "RevisionLog_articleId_fkey" FOREIGN KEY ("articleId") REFERENCES "Article" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "CorrectionRequest" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "targetUrl" TEXT NOT NULL,
    "proposedFix" TEXT NOT NULL,
    "evidenceUrl" TEXT,
    "requesterEmail" TEXT,
    "consent" BOOLEAN NOT NULL DEFAULT false,
    "status" TEXT NOT NULL DEFAULT 'open',
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "handledAt" DATETIME,
    "handledNote" TEXT
);

-- CreateTable
CREATE TABLE "AutomationLog" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "runAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "stage" TEXT NOT NULL,
    "level" TEXT NOT NULL DEFAULT 'info',
    "message" TEXT NOT NULL,
    "refType" TEXT,
    "refId" TEXT,
    "payload" TEXT
);

-- CreateTable
CREATE TABLE "AdminActivityLog" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT,
    "action" TEXT NOT NULL,
    "target" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "AdminActivityLog_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "_ArtistMusic" (
    "A" TEXT NOT NULL,
    "B" TEXT NOT NULL,
    CONSTRAINT "_ArtistMusic_A_fkey" FOREIGN KEY ("A") REFERENCES "Artist" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "_ArtistMusic_B_fkey" FOREIGN KEY ("B") REFERENCES "Music" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "_ArtistEvents" (
    "A" TEXT NOT NULL,
    "B" TEXT NOT NULL,
    CONSTRAINT "_ArtistEvents_A_fkey" FOREIGN KEY ("A") REFERENCES "Artist" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "_ArtistEvents_B_fkey" FOREIGN KEY ("B") REFERENCES "Event" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "_ArtistPrograms" (
    "A" TEXT NOT NULL,
    "B" TEXT NOT NULL,
    CONSTRAINT "_ArtistPrograms_A_fkey" FOREIGN KEY ("A") REFERENCES "Artist" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "_ArtistPrograms_B_fkey" FOREIGN KEY ("B") REFERENCES "Program" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "_ArticleArtists" (
    "A" TEXT NOT NULL,
    "B" TEXT NOT NULL,
    CONSTRAINT "_ArticleArtists_A_fkey" FOREIGN KEY ("A") REFERENCES "Article" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "_ArticleArtists_B_fkey" FOREIGN KEY ("B") REFERENCES "Artist" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "_ArticlePrograms" (
    "A" TEXT NOT NULL,
    "B" TEXT NOT NULL,
    CONSTRAINT "_ArticlePrograms_A_fkey" FOREIGN KEY ("A") REFERENCES "Article" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "_ArticlePrograms_B_fkey" FOREIGN KEY ("B") REFERENCES "Program" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "_ArticleEvents" (
    "A" TEXT NOT NULL,
    "B" TEXT NOT NULL,
    CONSTRAINT "_ArticleEvents_A_fkey" FOREIGN KEY ("A") REFERENCES "Article" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "_ArticleEvents_B_fkey" FOREIGN KEY ("B") REFERENCES "Event" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "_ArticleMusic" (
    "A" TEXT NOT NULL,
    "B" TEXT NOT NULL,
    CONSTRAINT "_ArticleMusic_A_fkey" FOREIGN KEY ("A") REFERENCES "Article" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "_ArticleMusic_B_fkey" FOREIGN KEY ("B") REFERENCES "Music" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateIndex
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");

-- CreateIndex
CREATE UNIQUE INDEX "Artist_slug_key" ON "Artist"("slug");

-- CreateIndex
CREATE UNIQUE INDEX "Music_slug_key" ON "Music"("slug");

-- CreateIndex
CREATE UNIQUE INDEX "Program_slug_key" ON "Program"("slug");

-- CreateIndex
CREATE UNIQUE INDEX "Event_slug_key" ON "Event"("slug");

-- CreateIndex
CREATE UNIQUE INDEX "Article_slug_key" ON "Article"("slug");

-- CreateIndex
CREATE UNIQUE INDEX "_ArtistMusic_AB_unique" ON "_ArtistMusic"("A", "B");

-- CreateIndex
CREATE INDEX "_ArtistMusic_B_index" ON "_ArtistMusic"("B");

-- CreateIndex
CREATE UNIQUE INDEX "_ArtistEvents_AB_unique" ON "_ArtistEvents"("A", "B");

-- CreateIndex
CREATE INDEX "_ArtistEvents_B_index" ON "_ArtistEvents"("B");

-- CreateIndex
CREATE UNIQUE INDEX "_ArtistPrograms_AB_unique" ON "_ArtistPrograms"("A", "B");

-- CreateIndex
CREATE INDEX "_ArtistPrograms_B_index" ON "_ArtistPrograms"("B");

-- CreateIndex
CREATE UNIQUE INDEX "_ArticleArtists_AB_unique" ON "_ArticleArtists"("A", "B");

-- CreateIndex
CREATE INDEX "_ArticleArtists_B_index" ON "_ArticleArtists"("B");

-- CreateIndex
CREATE UNIQUE INDEX "_ArticlePrograms_AB_unique" ON "_ArticlePrograms"("A", "B");

-- CreateIndex
CREATE INDEX "_ArticlePrograms_B_index" ON "_ArticlePrograms"("B");

-- CreateIndex
CREATE UNIQUE INDEX "_ArticleEvents_AB_unique" ON "_ArticleEvents"("A", "B");

-- CreateIndex
CREATE INDEX "_ArticleEvents_B_index" ON "_ArticleEvents"("B");

-- CreateIndex
CREATE UNIQUE INDEX "_ArticleMusic_AB_unique" ON "_ArticleMusic"("A", "B");

-- CreateIndex
CREATE INDEX "_ArticleMusic_B_index" ON "_ArticleMusic"("B");
