import Link from 'next/link';
import { prisma } from '@/lib/db';
import { WorkflowStatusBadge } from '@/components/badges';
import { ARTICLE_TYPE_LABEL, WORKFLOW_STATUS, WORKFLOW_STATUS_LABEL } from '@/lib/enums';
import { formatDate } from '@/lib/format';

export const dynamic = 'force-dynamic';

export default async function AdminArticlesPage({ searchParams }: { searchParams: Promise<{ status?: string }> }) {
  const { status } = await searchParams;
  const filter = status && (WORKFLOW_STATUS as readonly string[]).includes(status) ? status : undefined;

  const articles = await prisma.article.findMany({
    where: filter ? { status: filter } : {},
    orderBy: { updatedAt: 'desc' },
    include: { artists: { select: { stageName: true } } },
    take: 100,
  });

  return (
    <div>
      <h1 className="text-xl font-bold text-ink-900">기사 관리</h1>

      <div className="mt-3 flex flex-wrap gap-2 text-sm">
        <Link href="/admin/articles" className={`rounded-full px-3 py-1 ${!filter ? 'bg-brand-600 text-white' : 'bg-slate-100 text-ink-700'}`}>전체</Link>
        {WORKFLOW_STATUS.map((s) => (
          <Link key={s} href={`/admin/articles?status=${s}`} className={`rounded-full px-3 py-1 ${filter === s ? 'bg-brand-600 text-white' : 'bg-slate-100 text-ink-700'}`}>
            {WORKFLOW_STATUS_LABEL[s]}
          </Link>
        ))}
      </div>

      <ul className="mt-4 divide-y divide-slate-100 rounded-lg border border-slate-200">
        {articles.map((a) => (
          <li key={a.id} className="flex items-center justify-between gap-3 p-3">
            <div className="min-w-0 flex-1">
              <Link href={`/admin/articles/${a.id}`} className="block truncate text-sm font-medium text-ink-800 hover:text-brand-600">
                {a.autoGenerated && <span className="mr-1 rounded bg-slate-100 px-1 text-[11px] text-slate-500">자동</span>}
                {a.title}
              </Link>
              <p className="text-xs text-slate-400">
                {ARTICLE_TYPE_LABEL[a.type] ?? a.type} · {a.artists.map((x) => x.stageName).join(', ') || '연결된 가수 없음'} · 수정 {formatDate(a.updatedAt)}
              </p>
            </div>
            <div className="flex items-center gap-2">
              {a.qualityScore != null && <span className="text-xs text-slate-500">{a.qualityScore}점</span>}
              <WorkflowStatusBadge status={a.status} />
            </div>
          </li>
        ))}
        {articles.length === 0 && <li className="p-4 text-sm text-slate-500">해당 상태의 기사가 없습니다.</li>}
      </ul>
    </div>
  );
}
