import Link from 'next/link';
import { prisma } from '@/lib/db';
import { WorkflowStatusBadge } from '@/components/badges';
import { formatDate, formatDateTime } from '@/lib/format';

export const dynamic = 'force-dynamic';

function Stat({ label, value, href }: { label: string; value: number; href?: string }) {
  const inner = (
    <div className="rounded-xl border border-slate-200 p-4">
      <p className="text-2xl font-extrabold text-ink-900">{value}</p>
      <p className="text-xs text-slate-500">{label}</p>
    </div>
  );
  return href ? <Link href={href}>{inner}</Link> : inner;
}

export default async function AdminDashboard() {
  const now = new Date();
  const [counts, reviewQueue, recentLogs, openCorrections, staleProfiles, dueReviews, cancelledEvents] = await Promise.all([
    Promise.all([
      prisma.article.count({ where: { status: 'published' } }),
      prisma.article.count({ where: { status: 'review' } }),
      prisma.event.count({ where: { status: 'published' } }),
      prisma.artist.count({ where: { status: 'published' } }),
    ]),
    prisma.article.findMany({ where: { status: { in: ['review', 'verification_needed'] } }, orderBy: { createdAt: 'desc' }, take: 10 }),
    prisma.automationLog.findMany({ orderBy: { runAt: 'desc' }, take: 8 }),
    prisma.correctionRequest.count({ where: { status: 'open' } }),
    prisma.artist.findMany({ where: { status: 'published', lastFactCheckedAt: { lt: new Date(now.getTime() - 90 * 86400000) } }, take: 5 }),
    prisma.article.findMany({ where: { status: 'published', nextReviewAt: { lt: now } }, take: 5 }),
    prisma.event.findMany({ where: { status: 'published', eventStatus: { in: ['cancelled', 'postponed'] } }, take: 5 }),
  ]);
  const [published, inReview, events, artists] = counts;

  return (
    <div>
      <h1 className="text-xl font-bold text-ink-900">대시보드</h1>

      <div className="mt-4 grid grid-cols-2 gap-3 md:grid-cols-4">
        <Stat label="발행된 기사" value={published} href="/admin/articles" />
        <Stat label="검수 대기" value={inReview} href="/admin/articles?status=review" />
        <Stat label="공개 공연" value={events} />
        <Stat label="가수" value={artists} />
      </div>

      {/* 발행 후보 / 검수 대기 */}
      <section className="mt-8">
        <h2 className="text-lg font-bold text-ink-900">검수 대기 큐</h2>
        {reviewQueue.length ? (
          <ul className="mt-2 divide-y divide-slate-100 rounded-lg border border-slate-200">
            {reviewQueue.map((a) => (
              <li key={a.id} className="flex items-center justify-between gap-3 p-3">
                <Link href={`/admin/articles/${a.id}`} className="min-w-0 flex-1 truncate text-sm text-ink-800 hover:text-brand-600">
                  {a.autoGenerated && <span className="mr-1 rounded bg-slate-100 px-1 text-[11px] text-slate-500">자동</span>}
                  {a.title}
                </Link>
                <span className="flex items-center gap-2">
                  {a.qualityScore != null && <span className="text-xs text-slate-500">{a.qualityScore}점</span>}
                  <WorkflowStatusBadge status={a.status} />
                </span>
              </li>
            ))}
          </ul>
        ) : <p className="mt-2 text-sm text-slate-500">검수 대기 항목이 없습니다.</p>}
      </section>

      {/* 일일 점검 (§21) */}
      <section className="mt-8 grid gap-4 md:grid-cols-3">
        <div className="rounded-lg border border-slate-200 p-3">
          <p className="text-sm font-semibold text-ink-900">오래된 프로필 (90일+)</p>
          <ul className="mt-1 space-y-1 text-xs text-ink-700">
            {staleProfiles.length ? staleProfiles.map((a) => (
              <li key={a.id}>{a.stageName} · {a.lastFactCheckedAt ? formatDate(a.lastFactCheckedAt) : '미확인'}</li>
            )) : <li className="text-slate-400">없음</li>}
          </ul>
        </div>
        <div className="rounded-lg border border-slate-200 p-3">
          <p className="text-sm font-semibold text-ink-900">사실확인 예정 경과</p>
          <ul className="mt-1 space-y-1 text-xs text-ink-700">
            {dueReviews.length ? dueReviews.map((a) => (
              <li key={a.id} className="truncate">{a.title}</li>
            )) : <li className="text-slate-400">없음</li>}
          </ul>
        </div>
        <div className="rounded-lg border border-slate-200 p-3">
          <p className="text-sm font-semibold text-ink-900">취소·연기 공연</p>
          <ul className="mt-1 space-y-1 text-xs text-ink-700">
            {cancelledEvents.length ? cancelledEvents.map((e) => (
              <li key={e.id} className="truncate">{e.eventName}</li>
            )) : <li className="text-slate-400">없음</li>}
          </ul>
        </div>
      </section>

      {/* 자동화 로그 */}
      <section className="mt-8">
        <div className="flex items-baseline justify-between">
          <h2 className="text-lg font-bold text-ink-900">최근 자동화 로그</h2>
          <Link href="/admin/automation" className="text-sm text-brand-600 hover:underline">전체 보기</Link>
        </div>
        <ul className="mt-2 space-y-1 text-xs">
          {recentLogs.map((l) => (
            <li key={l.id} className="flex gap-2">
              <span className="w-32 shrink-0 text-slate-400">{formatDateTime(l.runAt)}</span>
              <span className={`w-16 shrink-0 font-semibold ${l.level === 'error' ? 'text-red-600' : l.level === 'warn' ? 'text-amber-600' : 'text-slate-500'}`}>{l.stage}</span>
              <span className="text-ink-700">{l.message}</span>
            </li>
          ))}
        </ul>
      </section>

      <p className="mt-8 rounded-lg bg-amber-50 p-3 text-xs text-amber-800">
        자동 발행 스위치: <strong>{process.env.AUTO_PUBLISH_ENABLED === 'true' ? 'ON' : 'OFF'}</strong>.
        대표 콘텐츠·파이프라인 검증 전까지 OFF를 유지하세요. 정정 요청 {openCorrections}건 대기 중.
      </p>
    </div>
  );
}
